[project]
name = "pytest-anki2"
version = "2.0.1"
description = "A pytest plugin for testing Anki add-ons"
authors = [
    { name = "Aristotelis P. (Glutanimate)" },
    { name = "Michal Krassowski" },
    { name = "Alexander Nilsson" },
]
requires-python = ">=3.9"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["anki", "development", "testing", "test", "pytest"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: User Interfaces",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
]
dependencies = [
    "pytest>=7.0",
    "pytest-qt~=4.4.0",
    "packaging>=21.3",
]

[project.urls]
Homepage = "https://github.com/Alexander-Nilsson/pytest-anki"
Repository = "https://github.com/Alexander-Nilsson/pytest-anki"
Download = "https://pypi.org/project/pytest-anki2/"

[project.entry-points.pytest11]
anki = "pytest_anki.plugin"

[project.optional-dependencies]
anki-2154 = ["aqt==2.1.54", "anki==2.1.54"]
anki-2165 = ["aqt==2.1.65", "anki==2.1.65"]
anki-2312 = ["aqt==23.12.1", "anki==23.12.1"]
anki-2411 = ["aqt==24.11", "anki==24.11"]
anki-2502 = ["aqt==25.02", "anki==25.02"]
anki-2507 = ["aqt==25.7", "anki==25.7"]
anki-2509 = ["aqt==25.9", "anki==25.9"]

qt5-2154 = ["PyQt5==5.15.5", "PyQt5-Qt5==5.15.2", "PyQtWebEngine==5.15.5"]
qt5-2165 = ["PyQt5==5.15.5", "PyQt5-Qt5==5.15.2", "PyQtWebEngine==5.15.5"]
qt5-2312 = ["PyQt5==5.15.5", "PyQt5-Qt5==5.15.2", "PyQtWebEngine==5.15.5"]
qt5-2411 = ["PyQt5==5.15.5", "PyQt5-Qt5==5.15.2", "PyQtWebEngine==5.15.5"]

qt6-2154 = [
    "PyQt6==6.3.1",
    "PyQt6-Qt6==6.3.1",
    "PyQt6-WebEngine==6.3.1",
    "PyQt6-WebEngine-Qt6==6.3.1",
]
qt6-2165 = [
    "PyQt6==6.5.0",
    "PyQt6-Qt6==6.5.0",
    "PyQt6-WebEngine==6.5.0",
    "PyQt6-WebEngine-Qt6==6.5.0",
]
qt6-2312 = [
    "PyQt6==6.6.1",
    "PyQt6-Qt6==6.6.1",
    "PyQt6-WebEngine==6.6.0",
    "PyQt6-WebEngine-Qt6==6.6.0",
]
qt6-2411 = [
    "PyQt6==6.6.1",
    "PyQt6-Qt6==6.6.1",
    "PyQt6-WebEngine==6.6.0",
    "PyQt6-WebEngine-Qt6==6.6.0",
]
qt6-2502 = [
    "PyQt6==6.6.1",
    "PyQt6-Qt6==6.6.1",
    "PyQt6-WebEngine==6.6.0",
    "PyQt6-WebEngine-Qt6==6.6.0",
]
qt6-2507 = [
    "PyQt6==6.7.0",
    "PyQt6-Qt6==6.7.0",
    "PyQt6-WebEngine==6.7.0",
    "PyQt6-WebEngine-Qt6>=6.7.0,<6.8.0",
]
qt6-2509 = [
    "PyQt6==6.8.0",
    "PyQt6-Qt6==6.8.1",
    "PyQt6-WebEngine==6.8.0",
    "PyQt6-WebEngine-Qt6==6.8.1",
]

recommended-plugins = [
    "pytest-xvfb~=3.1.1",
    "pytest-xdist>=3.0",
]

selenium = ["selenium>=3.141.0"]
web = ["selenium>=3.141.0"]

qt5 = ["PyQt5>=5.15.2", "PyQt5-Qt5>=5.15.2", "PyQtWebEngine>=5.15.5", "PyQt5-stubs>=5.15.2"]
qt6 = ["PyQt6>=6.3.1", "PyQt6-WebEngine>=6.3.1"]
qt6-system = ["PyQt6>=6.3.1", "PyQt6-WebEngine>=6.3.1"]
qt6-pypi = ["PyQt6>=6.3.1", "PyQt6-Qt6>=6.3.1", "PyQt6-WebEngine>=6.3.1", "PyQt6-WebEngine-Qt6>=6.3.1"]

[dependency-groups]
dev = [
    "ruff~=0.11.0",
    "ty>=0.0.44",
    "pre-commit>=4.0",
    "requests~=2.26",
    "pytest-anki2[recommended-plugins]",
    "protobuf>=6.33,<7",
    "pytest-cov>=4.0",
]
anki = ["aqt>=2.1.54", "anki>=2.1.54"]
qt5 = [
    "PyQt5>=5.15.2",
    "PyQt5-Qt5>=5.15.2",
    "PyQtWebEngine>=5.15.5",
    "PyQt5-stubs>=5.15.2",
]
qt6 = ["PyQt6>=6.3.1", "PyQt6-WebEngine>=6.3.1"]
qt6-system = ["PyQt6>=6.3.1", "PyQt6-WebEngine>=6.3.1"]
qt6-pypi = ["PyQt6>=6.3.1", "PyQt6-Qt6>=6.3.1", "PyQt6-WebEngine>=6.3.1", "PyQt6-WebEngine-Qt6>=6.3.1"]


[tool.uv]
constraint-dependencies = ["protobuf>=6.31.1,<7"]
default-groups = ["dev", "qt5", "qt6-pypi"]
conflicts = [
    [
        { extra = "anki-2154" },
        { extra = "anki-2165" },
        { extra = "anki-2312" },
        { extra = "anki-2411" },
        { extra = "anki-2502" },
        { extra = "anki-2507" },
        { extra = "anki-2509" },
    ],
    [
        { extra = "qt5-2154" },
        { extra = "qt5-2165" },
        { extra = "qt5-2312" },
        { extra = "qt5-2411" },
    ],
    [
        { extra = "qt6-2154" },
        { extra = "qt6-2165" },
        { extra = "qt6-2312" },
        { extra = "qt6-2411" },
        { extra = "qt6-2502" },
        { extra = "qt6-2507" },
        { extra = "qt6-2509" },
    ],
]

[tool.hatch.build.targets.sdist]
include = ["pytest_anki/py.typed"]

[tool.hatch.build.targets.wheel]
include = ["pytest_anki/py.typed"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
qt_api = "pyqt6"

[tool.ty.analysis]
allowed-unresolved-imports = ["**"]

[tool.ty.src]
exclude = ["tests/samples/"]

[tool.ruff]
line-length = 88
target-version = "py39"
extend-exclude = ["__pycache__", "tests/samples"]
lint.ignore = ["E203", "E266", "E501"]
lint.select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["pytest_anki"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = true

[tool.coverage.run]
source = ["pytest_anki"]
branch = true
omit = ["tests/*"]
